openapi: 3.0.0
info:
  title: AutoTrader
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /users/{userId}:
    get:
      description: Retrieve the information of the user with the matching user ID.
      operationId: get-users-userId
      parameters:
      - description: Id of an existing user.
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: integer
        style: simple
      - description: Your Api Key To Access This Site
        explode: true
        in: query
        name: key
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User Found
        "404":
          description: User Not Found
      summary: Get User Info by User ID
      tags: []
      x-eov-operation-handler: controllers/DefaultController
    patch:
      description: Update the infromation of an existing user.
      operationId: patch-users-userId
      parameters:
      - description: Id of an existing user.
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: 1985-10-02
            schema:
              properties:
                username:
                  description: The username that needs to be updated to
                  type: string
                password:
                  description: The new password that needs to be changed to
                  format: password
                  type: string
                email:
                  description: The new email address that needs to be changed to
                  format: email
                  type: string
              type: object
        description: Patch user properties to update.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User Updated
        "404":
          description: User Not Found
        "409":
          description: Email Already Taken
      summary: Update User Information
      x-eov-operation-handler: controllers/DefaultController
  /user:
    post:
      description: Create a new user.
      operationId: post-user
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          application/json:
            schema:
              properties:
                username:
                  description: The username of this account
                  type: string
                password:
                  description: The password of this account
                  format: password
                  type: string
                email:
                  description: The email address to receive the ticker notification
                  format: email
                  type: string
              required:
              - email
              - password
              - username
              type: object
        description: Post the necessary fields for the API to create a new user.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User Created
        "400":
          description: Missing Required Information
        "409":
          description: Email Already Taken
      summary: Create New User
      x-eov-operation-handler: controllers/DefaultController
  /users/{userId}/alerts:
    get:
      description: Get a list of alert that the user owns
      operationId: get-users-userId-alerts
      parameters:
      - explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Alert'
                type: array
          description: OK
        "204":
          description: No Content
        "401":
          description: 'Unauthorized: Insufficient Permission To View This Alert List'
        "404":
          description: 'Not Found: Alert List Does Not Exist'
      summary: Your GET endpoint
      tags: []
      x-eov-operation-handler: controllers/DefaultController
  /users/{userId}/alerts/{ticker}:
    get:
      description: Get the alert of a specific ticker for a user
      operationId: get-users-userId-alerts-ticker
      parameters:
      - explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: ticker
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Alert'
                type: array
          description: OK
        "401":
          description: 'Unauthorized: You Don''t Have Permission To View This Alert
            List'
        "404":
          description: 'Not Found: Alert List Does Not Exist'
      summary: Your GET endpoint
      tags: []
      x-eov-operation-handler: controllers/DefaultController
  /users/{userId}/alert:
    post:
      description: Create a new alert for a specific ticker on a specific event
      operationId: post-users-userId-alert
      parameters:
      - explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object_2'
        content:
          application/json:
            schema:
              properties:
                ticker:
                  type: string
                eventType:
                  enum:
                  - upCross
                  - downCross
                  type: string
                price:
                  type: number
              type: object
      responses:
        "201":
          description: Created
        "400":
          description: 'Bad Request: Ticker Not Found'
        "401":
          description: 'Unauthorized: Insufficient Permission To Create Alert On This
            User Id'
        "409":
          description: 'Conflict: Alert Already Exist'
      x-eov-operation-handler: controllers/DefaultController
  /users/{userId}/alerts/{ticker}/{alertId}:
    get:
      operationId: get-users-userId-alerts-ticker-alertId
      parameters:
      - explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: ticker
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: alertId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
          description: OK
        "401":
          description: 'Unauthorized: Insufficient Permission To View This Alert'
        "404":
          description: 'Not Found: Alert Does Not Exist'
      summary: Your GET endpoint
      tags: []
      x-eov-operation-handler: controllers/DefaultController
components:
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
    inline_object_2:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_2'
  schemas:
    User:
      example:
        emailVerified: true
        id: 1
        email: roger@xman.com
        username: rogerxman
        createDate: 2000-01-23
      properties:
        id:
          description: Unique identifier for the given user.
          example: 1
          type: integer
        username:
          description: The username of the user
          example: rogerxman
          type: string
        email:
          example: roger@xman.com
          format: email
          type: string
        emailVerified:
          description: Set to true if the user's email has been verified.
          type: boolean
        createDate:
          description: The date that the user was created.
          format: date
          type: string
      required:
      - email
      - emailVerified
      - id
      - username
      title: User
      type: object
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: 1997-10-31
          emailVerified: true
          signUpDate: 2019-08-24
    Alert:
      example:
        ticker: MSFT
        createTime: 2000-01-23
        price: 1.4658129805029452
        lastTriggerTime: 2000-01-23
        disabled: true
        id: 0
        eventType: upCross
        ownerId: 6
      properties:
        id:
          type: integer
        eventType:
          enum:
          - upCross
          - downCross
          example: upCross
          type: string
        ticker:
          example: MSFT
          type: string
        disabled:
          type: boolean
        createTime:
          format: date
          type: string
        lastTriggerTime:
          format: date
          type: string
        ownerId:
          type: integer
        price:
          type: number
      title: Alert
      type: object
    inline_object:
      properties:
        username:
          description: The username that needs to be updated to
          type: string
        password:
          description: The new password that needs to be changed to
          format: password
          type: string
        email:
          description: The new email address that needs to be changed to
          format: email
          type: string
      type: object
    inline_object_1:
      properties:
        username:
          description: The username of this account
          type: string
        password:
          description: The password of this account
          format: password
          type: string
        email:
          description: The email address to receive the ticker notification
          format: email
          type: string
      required:
      - email
      - password
      - username
      type: object
    inline_object_2:
      properties:
        ticker:
          type: string
        eventType:
          enum:
          - upCross
          - downCross
          type: string
        price:
          type: number
      type: object
  securitySchemes: {}
