GET http://localhost:3000/ping HTTP/1.1

### 

GET http://localhost:3000/users/2 HTTP/1.1
content-type: application/json

###

PATCH http://localhost:3000/users/1 HTTP/1.1
content-type: application/json

{
    "username": "roger",
    "password": "greater",
    "email": "new@email.com"
}

###

POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "username": "newnew",
    "password": "newnewnew",
    "email": "sample@newnewnew.com"
}

###

GET http://localhost:3000/users/1/alerts HTTP/1.1

###

GET http://localhost:3000/users/1/alerts/MSFT HTTP/1.1

###

POST http://localhost:3000/users/1/alert HTTP/1.1
content-type: application/json

{
    "ticker": "AMAZ",
    "eventType": "upCross",
    "price": 12.34
}

###
GET http://localhost:3000/users/1/alerts/AMAZ/4 HTTP/1.1