GET http://localhost:3000/ping HTTP/1.1

### 

GET http://localhost:3000/users/5 HTTP/1.1
content-type: application/json

###

PATCH http://localhost:3000/users/1 HTTP/1.1
content-type: application/json

{
    "username": "great",
    "password": "greater",
    "email": "new@email.com"
}

###

POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "username": "fasdfasdfzvxc",
    "password": "fqgascvabgreaegv",
    "email": "sample@asdfvasdfvasdrgqwdfa.com"
}

###

GET http://localhost:3000/users/1/alerts HTTP/1.1

###

GET http://localhost:3000/users/1/alerts/MSFT HTTP/1.1

###

POST http://localhost:3000/users/1/alert HTTP/1.1
content-type: application/json

{
    "ticker": "MSFT",
    "eventType": "upCross",
    "price": 43.21
}

###
GET http://localhost:3000/users/1/alerts/MSFT/1 HTTP/1.1