### Get /ping

GET http://localhost:3000/ping HTTP/1.1

### Get /users/<user_id>

GET http://localhost:3000/users/5 HTTP/1.1
content-type: application/json

### Patch /users/<user_id>

PATCH http://localhost:3000/users/1 HTTP/1.1
content-type: application/json

{
    "username": "great",
    "password": "greater",
    "email": "new@email.com"
}

### Post /user

POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "username": "fasdfasdfzvxc",
    "password": "fqgascvabgreaegv",
    "email": "sample@asdfvasdfvasdrgqwdfa.com"
}

### Get /users/<user_id>/alerts

GET http://localhost:3000/users/1/alerts HTTP/1.1

### Get /users/<user_id>/alerts/<ticker>

GET http://localhost:3000/users/1/alerts/MSFT HTTP/1.1

### Post /users/<user_id>/alert

POST http://localhost:3000/users/1/alert HTTP/1.1
content-type: application/json

{
    "ticker": "MSFT",
    "eventType": "upCross",
    "price": 43.21
}

### Get /users/<user_id>/alerts/<ticker>/<alert_id>

GET http://localhost:3000/users/1/alerts/MSFT/1 HTTP/1.1

### Post /login

Post http://localhost:3000/login