# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Alert(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, event_type: str=None, ticker: str=None, disabled: bool=None, create_time: date=None, last_trigger_time: date=None, owner_id: int=None, price: float=None):  # noqa: E501
        """Alert - a model defined in Swagger

        :param id: The id of this Alert.  # noqa: E501
        :type id: int
        :param event_type: The event_type of this Alert.  # noqa: E501
        :type event_type: str
        :param ticker: The ticker of this Alert.  # noqa: E501
        :type ticker: str
        :param disabled: The disabled of this Alert.  # noqa: E501
        :type disabled: bool
        :param create_time: The create_time of this Alert.  # noqa: E501
        :type create_time: date
        :param last_trigger_time: The last_trigger_time of this Alert.  # noqa: E501
        :type last_trigger_time: date
        :param owner_id: The owner_id of this Alert.  # noqa: E501
        :type owner_id: int
        :param price: The price of this Alert.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'id': int,
            'event_type': str,
            'ticker': str,
            'disabled': bool,
            'create_time': date,
            'last_trigger_time': date,
            'owner_id': int,
            'price': float
        }

        self.attribute_map = {
            'id': 'id',
            'event_type': 'eventType',
            'ticker': 'ticker',
            'disabled': 'disabled',
            'create_time': 'createTime',
            'last_trigger_time': 'lastTriggerTime',
            'owner_id': 'ownerId',
            'price': 'price'
        }
        self._id = id
        self._event_type = event_type
        self._ticker = ticker
        self._disabled = disabled
        self._create_time = create_time
        self._last_trigger_time = last_trigger_time
        self._owner_id = owner_id
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'Alert':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Alert of this Alert.  # noqa: E501
        :rtype: Alert
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Alert.


        :return: The id of this Alert.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Alert.


        :param id: The id of this Alert.
        :type id: int
        """

        self._id = id

    @property
    def event_type(self) -> str:
        """Gets the event_type of this Alert.


        :return: The event_type of this Alert.
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type: str):
        """Sets the event_type of this Alert.


        :param event_type: The event_type of this Alert.
        :type event_type: str
        """
        allowed_values = ["upCross", "downCross"]  # noqa: E501
        if event_type not in allowed_values:
            raise ValueError(
                "Invalid value for `event_type` ({0}), must be one of {1}"
                .format(event_type, allowed_values)
            )

        self._event_type = event_type

    @property
    def ticker(self) -> str:
        """Gets the ticker of this Alert.


        :return: The ticker of this Alert.
        :rtype: str
        """
        return self._ticker

    @ticker.setter
    def ticker(self, ticker: str):
        """Sets the ticker of this Alert.


        :param ticker: The ticker of this Alert.
        :type ticker: str
        """

        self._ticker = ticker

    @property
    def disabled(self) -> bool:
        """Gets the disabled of this Alert.


        :return: The disabled of this Alert.
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled: bool):
        """Sets the disabled of this Alert.


        :param disabled: The disabled of this Alert.
        :type disabled: bool
        """

        self._disabled = disabled

    @property
    def create_time(self) -> date:
        """Gets the create_time of this Alert.


        :return: The create_time of this Alert.
        :rtype: date
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time: date):
        """Sets the create_time of this Alert.


        :param create_time: The create_time of this Alert.
        :type create_time: date
        """

        self._create_time = create_time

    @property
    def last_trigger_time(self) -> date:
        """Gets the last_trigger_time of this Alert.


        :return: The last_trigger_time of this Alert.
        :rtype: date
        """
        return self._last_trigger_time

    @last_trigger_time.setter
    def last_trigger_time(self, last_trigger_time: date):
        """Sets the last_trigger_time of this Alert.


        :param last_trigger_time: The last_trigger_time of this Alert.
        :type last_trigger_time: date
        """

        self._last_trigger_time = last_trigger_time

    @property
    def owner_id(self) -> int:
        """Gets the owner_id of this Alert.


        :return: The owner_id of this Alert.
        :rtype: int
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id: int):
        """Sets the owner_id of this Alert.


        :param owner_id: The owner_id of this Alert.
        :type owner_id: int
        """

        self._owner_id = owner_id

    @property
    def price(self) -> float:
        """Gets the price of this Alert.


        :return: The price of this Alert.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Alert.


        :param price: The price of this Alert.
        :type price: float
        """

        self._price = price
