# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WatchlistRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, owner_id: int=None, watchlist: List[str]=None):  # noqa: E501
        """WatchlistRequest - a model defined in Swagger

        :param owner_id: The owner_id of this WatchlistRequest.  # noqa: E501
        :type owner_id: int
        :param watchlist: The watchlist of this WatchlistRequest.  # noqa: E501
        :type watchlist: List[str]
        """
        self.swagger_types = {
            'owner_id': int,
            'watchlist': List[str]
        }

        self.attribute_map = {
            'owner_id': 'ownerId',
            'watchlist': 'watchlist'
        }
        self._owner_id = owner_id
        self._watchlist = watchlist

    @classmethod
    def from_dict(cls, dikt) -> 'WatchlistRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WatchlistRequest of this WatchlistRequest.  # noqa: E501
        :rtype: WatchlistRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def owner_id(self) -> int:
        """Gets the owner_id of this WatchlistRequest.


        :return: The owner_id of this WatchlistRequest.
        :rtype: int
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id: int):
        """Sets the owner_id of this WatchlistRequest.


        :param owner_id: The owner_id of this WatchlistRequest.
        :type owner_id: int
        """

        self._owner_id = owner_id

    @property
    def watchlist(self) -> List[str]:
        """Gets the watchlist of this WatchlistRequest.


        :return: The watchlist of this WatchlistRequest.
        :rtype: List[str]
        """
        return self._watchlist

    @watchlist.setter
    def watchlist(self, watchlist: List[str]):
        """Sets the watchlist of this WatchlistRequest.


        :param watchlist: The watchlist of this WatchlistRequest.
        :type watchlist: List[str]
        """

        self._watchlist = watchlist
