"""Add username in db user table

Revision ID: 030943a2a1c2
Revises: 8617f5a47509
Create Date: 2021-01-24 18:33:03.938711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030943a2a1c2'
down_revision = '8617f5a47509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.NCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
