"""Add alert table

Revision ID: 3239bf1bbb9c
Revises: 030943a2a1c2
Create Date: 2021-01-24 20:06:25.174828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3239bf1bbb9c'
down_revision = '030943a2a1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.NCHAR(length=16), nullable=False),
    sa.Column('ticker', sa.NCHAR(length=16), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('deleted_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_triggered_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_inspected_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_alert')
    # ### end Alembic commands ###
