"""Add user table into db

Revision ID: 7f687f4a6459
Revises: c381b61346eb
Create Date: 2021-01-24 17:49:39.078575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f687f4a6459'
down_revision = 'c381b61346eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.NCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.NCHAR(length=255), nullable=False),
    sa.Column('password_salt', sa.NCHAR(length=255), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_login_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.NCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_user')
    # ### end Alembic commands ###
