"""Remove user agent from user schema

Revision ID: 8617f5a47509
Revises: 7f687f4a6459
Create Date: 2021-01-24 18:28:57.401168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8617f5a47509'
down_revision = '7f687f4a6459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.NCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
