"""add strategy relate tables

Revision ID: f32451caf180
Revises: 3239bf1bbb9c
Create Date: 2021-03-13 00:29:40.687074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32451caf180'
down_revision = '3239bf1bbb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.NCHAR(length=1024), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('strategy_type', sa.Enum('SPAC', 'BUY_LOW_SELL_HIGH', 'LONG_HOLD', 'SHORT_HOLD', 'DAY_TRADE', 'DIVIDEND_INVESTMENT', name='dbstrategytype'), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_modified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('ticker', sa.NCHAR(length=100), nullable=False),
    sa.Column('term', sa.Enum('LONG_TERM', 'SHORT_TERM', 'MIDDLE_TERM', 'FLEX_TERM', name='dbtradeterm'), nullable=True),
    sa.Column('sector', sa.Enum('BASIC_MATERIALS', 'INDUSTRIALS', 'FINANCIAL_SERVICES', 'ENERGY', 'CONSUMER_CYCLICAL', 'TECHNOLOGY', 'COMMUNICATION_SERVICES', 'REAL_ESTATE', 'HEALTHCARE', 'CONSUMER_DEFENSIVE', 'UTILITIES', name='dbstocksector'), nullable=False),
    sa.Column('goal_summary', sa.NCHAR(length=1024), nullable=True),
    sa.Column('target_prices', sa.PickleType(), nullable=True),
    sa.Column('stop_loss_prices', sa.PickleType(), nullable=True),
    sa.Column('cost_basis', sa.FLOAT(precision=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_return', sa.FLOAT(precision=2), nullable=False),
    sa.Column('dividend_return', sa.FLOAT(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_strategy_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_modified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('operator', sa.Enum('NONE', 'BUY', 'SELL', 'SELL_COVERED_CALL', 'EXPIRE_COVERED_CALL', 'BUY_COVERED_CALL', 'BUY_OPEN_CALL', 'EXPIRE_CALL', 'SELL_CLOSE_CALL', 'BUY_OPEN_PUT', 'EXPIRE_PUT', 'SELL_CLOSE_PUT', 'CHANGE_TARGET_PRICES', 'CHANGE_STOP_LOSS_PRICES', 'DIVIDEND_EARNING', name='dbtradeoperation'), nullable=False),
    sa.Column('comment', sa.NCHAR(length=1024), nullable=True),
    sa.Column('price', sa.FLOAT(precision=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('target_prices', sa.PickleType(), nullable=True),
    sa.Column('stop_loss_prices', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['db_strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_strategy_activity')
    op.drop_table('db_strategy')
    # ### end Alembic commands ###
